- name: admin keys are inserted
  authorized_key:
    user: "{{ admin_user }}"
    key: "{{ item }}"
    state: present
  loop: "{{ admin_pubkeys }}"

- name: admin tools are installed
  apt:
    name:
      - htop
      - tmux
    state: present
