- hosts: dokku

  become: yes

  roles:
    - role: packages
      tags: ["packages"]

    - role: firewall
      tags: ["firewall"]

    - role: docker
      tags: ["docker"]

    - role: dokku
      tags: ["dokku"]

    - role: dokku-nginx
      tags: ["dokku", "nginx"]

    - role: mackerel
      tags: ["mackerel"]
