- hosts: dokku

  become: yes

  roles:
    - role: packages
      tags: ["packages"]

    - role: admin
      tags: ["admin"]

    - role: firewall
      tags: ["firewall"]

    - role: fail2ban
      tags: ["fail2ban"]

    - role: docker
      tags: ["docker"]

    - role: dokku
      tags: ["dokku"]

    - role: dokku-nginx
      tags: ["dokku-nginx"]

    - role: mackerel
      tags: ["mackerel"]
