- name: packagecloud repository key is registered
  apt_key:
    id: 418a7f2fb0e1e6e7eabf6fe8c2e73424d59097ab
    url: https://packagecloud.io/gpg.key
    state: present

- name: dokku repository is registered
  apt_repository:
    repo: deb https://packagecloud.io/dokku/dokku/debian/ {{ ansible_lsb.codename }} main
    state: present

- name: dokku web configuration is disabled
  debconf:
    name: dokku
    question: dokku/web_config
    vtype: boolean
    value: false

- name: dokku is configured to use vhost
  debconf:
    name: dokku
    question: dokku/vhost_enable
    vtype: boolean
    value: true

- name: dokku host is set
  debconf:
    name: dokku
    question: dokku/hostname
    vtype: string
    value: "{{ ansible_fqdn }}"

- name: dokku is configured to skip initial ssh key setup
  debconf:
    name: dokku
    question: dokku/skip_key_file
    vtype: boolean
    value: true

- name: dokku is installed
  apt:
    name: dokku
    state: present

- name: dokku plugin dependencies are installed
  command: dokku plugin:install-dependencies --core

- name: dokku additional plugins are installed
  command: dokku plugin:install "{{ item.url }}" "{{ item.name }}"
  args:
    creates: "/var/lib/dokku/plugins/available/{{ item.name }}"
  with_items:
    - { url: "https://github.com/dokku/dokku-postgres.git", name: postgres }
    - { url: "https://github.com/dokku/dokku-redis.git", name: redis }
    - { url: "https://github.com/dokku/dokku-rethinkdb.git", name: rethinkdb }

- name: dokku user may use ssh
  user:
    name: dokku
    groups: ssh_users
    append: yes

- name: dokku recognizes primary key
  shell: dokku ssh-keys:remove admin; echo "{{ primary_pubkey }}" | dokku ssh-keys:add admin

- name: dokku extra admin keys are removed
  shell: dokku ssh-keys:list | grep -Eo "\badmin[[:digit:]]+" | xargs -rL1 dokku ssh-keys:remove

- name: dokku extra admin keys are inserted
  shell: echo "{{ primary_pubkey }}" | dokku ssh-keys:add "admin{{ index + 1 }}"
  loop: "{{ admin_pubkeys }}"
  loop_control:
    index_var: index
