- name: firewall scripts are present
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    mode: 0744
  loop:
    - ipv4_firewall.sh
    - ipv6_firewall.sh

- name: firewall services are present
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
  loop:
    - ipv4_firewall.service
    - ipv6_firewall.service

- name: firewall services are activated
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - ipv4_firewall
    - ipv6_firewall
  notify:
    - restart docker
