- name: nginx ssl files are present
  copy:
    src: "{{ item }}"
    dest: /etc/nginx/ssl/
  with_items:
    - production/origin.cert
    - production/origin.key
  notify:
    - reload nginx

- name: nginx is configured as ssl reverse proxy
  copy:
    src: nginx-https-reverse-proxy.conf
    dest: /etc/nginx/conf.d/00-https-reverse-proxy.conf
  notify:
    - reload nginx

- name: nginx default vhost is blocked
  copy:
    src: nginx-block-default-vhost.conf
    dest: /etc/nginx/conf.d/00-block-default-vhost.conf
  notify:
    - reload nginx

- name: nginx default site is disabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - reload nginx
